# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - myapp100translator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://azurecontregistry1.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f0ff51909f9d49d0a18e729e46a2ec2e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f9f733c1ebe84a2db81a75ac168c1eec }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: azurecontregistry1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f0ff51909f9d49d0a18e729e46a2ec2e }}/myapp100:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myapp100translator'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_5a544caa305e498b9bf0fd55eb29de2c }}
        images: 'azurecontregistry1.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f0ff51909f9d49d0a18e729e46a2ec2e }}/myapp100:${{ github.sha }}'